[package]
name = "pumlformat"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
fancy-regex = "0.14"
anyhow = "1.0.64"
log = "0.4.26"
env_logger = "0.11.6"
